"""Generate and export evaluation reports."""

import json
from datetime import datetime
from pathlib import Path

import config


def save_report(
    video_name: str,
    scored_rubric: dict,
    narrative: str,
    character_info: dict,
    video_metadata: dict,
    transcript: str,
) -> Path:
    """Save full report as JSON + human-readable text to outputs directory."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    stem = Path(video_name).stem
    out_dir = config.OUTPUTS_DIR / f"{stem}_{timestamp}"
    out_dir.mkdir(parents=True, exist_ok=True)

    # ── Full JSON report ──────────────────────────────────────────────
    full_report = {
        "video": video_name,
        "metadata": video_metadata,
        "generated_at": datetime.now().isoformat(),
        "characters": character_info,
        "rubric": scored_rubric,
        "narrative": narrative,
        "transcript": transcript,
    }
    json_path = out_dir / "report.json"
    json_path.write_text(json.dumps(full_report, indent=2, ensure_ascii=False), encoding="utf-8")

    # ── Human-readable text report ────────────────────────────────────
    text_path = out_dir / "report.txt"
    lines = [
        "=" * 70,
        f"  SIMULATION VIDEO EVALUATION REPORT",
        f"  Video: {video_name}",
        f"  Duration: {video_metadata.get('duration_sec', '?')}s | Resolution: {video_metadata.get('resolution', '?')}",
        f"  Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "=" * 70,
        "",
    ]

    # Rubric transparency notice
    if scored_rubric.get("auto_generated"):
        lines.append("[NOTE] This rubric was AUTO-GENERATED by the AI model based on")
        lines.append("video content. It was NOT provided by the user. Review rubric")
        lines.append("items for appropriateness before using scores for assessment.")
        lines.append("")

    # Character summary
    lines.append("TEAM MEMBERS IDENTIFIED")
    lines.append("-" * 40)
    for c in character_info.get("characters", []):
        lines.append(f"  {c.get('label', '?')}: {c.get('visual_id', '?')}")
    lines.append("")

    # Scored rubric
    lines.append("RUBRIC EVALUATION")
    lines.append("-" * 40)
    total_yes = total_partial = total_no = total_na = 0
    for cat in scored_rubric.get("categories", []):
        lines.append(f"\n  [{cat['name']}]")
        for item in cat.get("items", []):
            score = item.get("score", "?")
            icon = {"Yes": "+", "Partial": "~", "No": "-", "N/A": " "}.get(score, "?")
            lines.append(f"    [{icon}] {item.get('id', '')} {item['text']}: {score}")
            if item.get("evidence"):
                lines.append(f"        Evidence: {item['evidence']}")

            if score == "Yes":
                total_yes += 1
            elif score == "Partial":
                total_partial += 1
            elif score == "No":
                total_no += 1
            elif score == "N/A":
                total_na += 1

    scored_total = total_yes + total_partial + total_no
    lines.append(f"\n  SUMMARY: {total_yes} Yes / {total_partial} Partial / {total_no} No / {total_na} N/A")
    if scored_total > 0:
        pct = round((total_yes + 0.5 * total_partial) / scored_total * 100, 1)
        lines.append(f"  SCORE: {pct}% (Yes=full credit, Partial=half credit)")
    lines.append("")

    # Narrative
    lines.append("NARRATIVE REPORT")
    lines.append("-" * 40)
    lines.append(narrative)
    lines.append("")

    # Transcript
    if transcript:
        lines.append("AUDIO TRANSCRIPT")
        lines.append("-" * 40)
        lines.append(transcript[:3000])
        if len(transcript) > 3000:
            lines.append("... [truncated, see report.json for full transcript]")

    text_path.write_text("\n".join(lines), encoding="utf-8")

    return out_dir
